<!-- ======= Contact Section ======= -->
<section id="contact" class="contact">
    <div class="container" data-aos="fade-up">
        <header class="section-header">
            <p>Privacy policy</p>
        </header>

        <div class="row gy-4">
            <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. In placerat nibh ipsum, quis ornare dolor luctus quis. Vivamus sem elit, feugiat nec iaculis eu, semper sed neque. Mauris fringilla lectus non elit congue finibus. Donec commodo rutrum mauris, sed consequat lorem porta ac. Etiam turpis ipsum, varius a purus in, porttitor tempor dolor. In dictum hendrerit nisl, ac iaculis dolor gravida pellentesque. Nunc enim dolor, congue cursus purus eget, imperdiet viverra lectus. Fusce bibendum lacinia nisi in faucibus. Donec vitae efficitur orci. Vivamus ac odio arcu. Nullam ut justo quam. Vivamus congue et sem vitae commodo. Nam imperdiet leo eget risus sodales vulputate. In purus dui, rhoncus non libero sed, consectetur fringilla sapien. Etiam egestas aliquam augue, sit amet tempus nulla faucibus et. 
            Curabitur egestas massa sit amet tincidunt luctus. Vestibulum vehicula convallis sapien sit amet fermentum. Duis ut elementum lectus. Nulla gravida convallis congue. Morbi odio arcu, volutpat dignissim lorem iaculis, lacinia scelerisque nibh. Suspendisse in commodo erat, quis pulvinar dolor. Suspendisse tempus arcu libero, sed aliquet leo auctor sed. Mauris pretium tincidunt eros, vel iaculis dui pulvinar elementum. Sed in eros augue. Nam in nisi leo.
            Maecenas ut feugiat nunc. Proin vel rutrum libero. Proin ipsum purus, dapibus vitae laoreet eu, egestas ac neque. Fusce vitae tristique dolor, eu vulputate diam. Nulla velit risus, mattis at fermentum ut, scelerisque et mi. Curabitur quis ante consectetur, sagittis lectus non, auctor dui. Morbi cursus gravida metus a molestie. Integer et scelerisque libero. Quisque euismod felis vitae tortor consectetur ultrices. Suspendisse volutpat justo eu fringilla mollis. Sed pharetra erat eu eleifend cursus. Ut dui tellus, molestie id purus rhoncus, maximus mattis tortor. Nunc sit amet elit pharetra, vestibulum nisi a, hendrerit erat. Donec malesuada sodales vulputate. Nulla vehicula ullamcorper enim eu congue. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
            Pellentesque tempor, urna ac consectetur iaculis, diam odio rutrum elit, at dapibus diam felis at nisi. Nunc egestas purus nec venenatis aliquam. Mauris condimentum arcu sit amet ipsum vestibulum convallis. Mauris urna augue, imperdiet ac condimentum in, interdum vel tortor. Etiam vehicula enim magna, a interdum turpis luctus non. Aliquam convallis risus hendrerit facilisis imperdiet. Phasellus quam erat, aliquet sed tristique sodales, consequat non risus. Aenean quis placerat nisi. Maecenas tincidunt rutrum odio et porta. Integer euismod, neque vel laoreet euismod, eros turpis fringilla libero, non venenatis est leo at nulla. Suspendisse potenti. Morbi a iaculis tellus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla ut rhoncus nibh, dictum volutpat mauris. Maecenas ultrices vitae nunc nec venenatis.
            Fusce dictum sapien ut dui accumsan, sit amet rutrum velit accumsan. Sed euismod erat vitae urna imperdiet, et placerat dolor ultrices. Duis faucibus consequat venenatis. Sed est lorem, faucibus eu accumsan nec, egestas nec lacus. Fusce placerat pellentesque neque sed aliquam. Sed eu convallis neque. Fusce vel ante tempor, blandit nisl nec, auctor eros. Sed nec ante felis. Donec ullamcorper fermentum pretium. Praesent eget condimentum turpis, quis tristique dolor. Ut sed consequat justo, id luctus erat. Nullam convallis imperdiet justo. Donec a massa aliquam, tempor lectus ac, laoreet velit. Quisque eu nulla quis velit dictum vulputate vitae sed mi. Praesent maximus porta lectus quis lobortis. Etiam hendrerit ultricies dolor, porta semper ligula viverra nec.
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. In placerat nibh ipsum, quis ornare dolor luctus quis. Vivamus sem elit, feugiat nec iaculis eu, semper sed neque. Mauris fringilla lectus non elit congue finibus. Donec commodo rutrum mauris, sed consequat lorem porta ac. Etiam turpis ipsum, varius a purus in, porttitor tempor dolor. In dictum hendrerit nisl, ac iaculis dolor gravida pellentesque. Nunc enim dolor, congue cursus purus eget, imperdiet viverra lectus. Fusce bibendum lacinia nisi in faucibus. Donec vitae efficitur orci. Vivamus ac odio arcu. Nullam ut justo quam. Vivamus congue et sem vitae commodo. Nam imperdiet leo eget risus sodales vulputate. In purus dui, rhoncus non libero sed, consectetur fringilla sapien. Etiam egestas aliquam augue, sit amet tempus nulla faucibus et.
            Curabitur egestas massa sit amet tincidunt luctus. Vestibulum vehicula convallis sapien sit amet fermentum. Duis ut elementum lectus. Nulla gravida convallis congue. Morbi odio arcu, volutpat dignissim lorem iaculis, lacinia scelerisque nibh. Suspendisse in commodo erat, quis pulvinar dolor. Suspendisse tempus arcu libero, sed aliquet leo auctor sed. Mauris pretium tincidunt eros, vel iaculis dui pulvinar elementum. Sed in eros augue. Nam in nisi leo.
            Maecenas ut feugiat nunc. Proin vel rutrum libero. Proin ipsum purus, dapibus vitae laoreet eu, egestas ac neque. Fusce vitae tristique dolor, eu vulputate diam. Nulla velit risus, mattis at fermentum ut, scelerisque et mi. Curabitur quis ante consectetur, sagittis lectus non, auctor dui. Morbi cursus gravida metus a molestie. Integer et scelerisque libero. Quisque euismod felis vitae tortor consectetur ultrices. Suspendisse volutpat justo eu fringilla mollis. Sed pharetra erat eu eleifend cursus. Ut dui tellus, molestie id purus rhoncus, maximus mattis tortor. Nunc sit amet elit pharetra, vestibulum nisi a, hendrerit erat. Donec malesuada sodales vulputate. Nulla vehicula ullamcorper enim eu congue. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
            Pellentesque tempor, urna ac consectetur iaculis, diam odio rutrum elit, at dapibus diam felis at nisi. Nunc egestas purus nec venenatis aliquam. Mauris condimentum arcu sit amet ipsum vestibulum convallis. Mauris urna augue, imperdiet ac condimentum in, interdum vel tortor. Etiam vehicula enim magna, a interdum turpis luctus non. Aliquam convallis risus hendrerit facilisis imperdiet. Phasellus quam erat, aliquet sed tristique sodales, consequat non risus. Aenean quis placerat nisi. Maecenas tincidunt rutrum odio et porta. Integer euismod, neque vel laoreet euismod, eros turpis fringilla libero, non venenatis est leo at nulla. Suspendisse potenti. Morbi a iaculis tellus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla ut rhoncus nibh, dictum volutpat mauris. Maecenas ultrices vitae nunc nec venenatis.
            Fusce dictum sapien ut dui accumsan, sit amet rutrum velit accumsan. Sed euismod erat vitae urna imperdiet, et placerat dolor ultrices. Duis faucibus consequat venenatis. Sed est lorem, faucibus eu accumsan nec, egestas nec lacus. Fusce placerat pellentesque neque sed aliquam. Sed eu convallis neque. Fusce vel ante tempor, blandit nisl nec, auctor eros. Sed nec ante felis. Donec ullamcorper fermentum pretium. Praesent eget condimentum turpis, quis tristique dolor. Ut sed consequat justo, id luctus erat. Nullam convallis imperdiet justo. Donec a massa aliquam, tempor lectus ac, laoreet velit. Quisque eu nulla quis velit dictum vulputate vitae sed mi. Praesent maximus porta lectus quis lobortis. Etiam hendrerit ultricies dolor, porta semper ligula viverra nec.
            </p>
        </div>
    </div>
</section><!-- End Contact Section -->